export const API_URL = 'https://localhost:44349/api'

export const FURNACE_FIELDS = 
[
    { name: 'numberOfFurnace', description: 'Номер доменной печи' },
    { name: 'usefulVolumeOfFurnace', description: 'Полезный объем печи, м3' },
    { name: 'usefulHeightOfFurnace', description: 'Полезная высота печи, мм' },
    { name: 'diameterOfColoshnik', description: 'Диаметр колошника, мм' },
    { name: 'diameterOfRaspar', description: 'Диаметр распара, мм' },
    { name: 'diameterOfHorn', description: 'Диаметр горна, мм' },
    { name: 'heightOfHorn', description: 'Высота горна, мм' },
    { name: 'heightOfTuyeres', description: 'Высота фурм, мм' },
    { name: 'heightOfZaplechiks', description: 'Высота заплечников, мм' },
    { name: 'heightOfRaspar', description: 'Высота распара, мм' },
    { name: 'heightOfShaft', description: 'Высота шахты, мм' },
    { name: 'heightOfColoshnik', description: 'Высота колошника, мм' },
    { name: 'establishedLevelOfEmbankment', description: 'Установленный уровень насыпи, мм' },
    { name: 'numberOfTuyeres', description: 'Число фурм, шт' },
    { name: 'dailyСapacityOfFurnace', description: 'Суточная производительность печи, т чугуна/сутки' },
    { name: 'specificConsumptionOfCoke', description: 'Удельный расход кокса, кг/т чугуна' },
    { name: 'specificConsumptionOfZRM', description: 'Удельный расход ЖРМ, кг/т чугуна' },
    { name: 'shareOfPelletsInCharge', description: 'Доля окатышей в шихте, доли ед.' },
    // ПАРАМЕТРЫ ДУТЬЯ
    { name: 'blastConsumption', description: 'Расход дутья, м3/мин' },
    { name: 'blastTemperature', description: 'Температура дутья, С' },
    { name: 'blastPressure', description: 'Давление дутья, ати' },
    { name: 'blastHumidity', description: 'Влажность дутья, г/м3' },
    { name: 'oxygenContentInBlast', description: 'Содержание кислорода в дутье, %' },
    { name: 'naturalGasConsumption', description: 'Расход природного газа, м3/т чугуна' },
    // ПАРАМЕТРЫ КОЛОШНИКОВОГО ГАЗА
    { name: 'coloshGasTemperature', description: 'Температура колошникового газа, С' },
    { name: 'coloshGasPressure', description: 'Давление колошникового газа, ати' },
    // СОСТАВ КОЛОШНИКОВОГО ГАЗА
    { name: 'coloshGas_CO', description: 'CO в колошниковом газе, %' },
    { name: 'coloshGas_CO2', description: 'CO2 в колошниковом газе, %' },
    { name: 'coloshGas_H2', description: 'H2 в колошниковом газе, %' },
    // СОСТАВ ЧУГУНА
    { name: 'chugun_SI', description: 'Содержание Si в чугуне, %' },
    { name: 'chugun_MN', description: 'Содержание Mn в чугуне, %' },
    { name: 'chugun_P', description: 'Содержание P в чугуне, %' },
    { name: 'chugun_S', description: 'Содержание S в чугуне, %' },
    { name: 'chugun_C', description: 'Содержание C в чугуне, %' },
    // СОСТАВ КОКСА
    { name: 'ashContentInCoke', description: 'Содержание золы в коксе, %' },
    { name: 'volatileContentInCoke', description: 'Содержание летучих в коксе, %' },
    { name: 'sulfurContentInCoke', description: 'Содержание серы в коксе, %' },
    { name: 'specificSlagYield', description: 'Удельный выход шлака (по данным тех. отчёта), кг/т чугуна' },
    { name: 'heatCapacityOfAgglomerate', description: 'Теплоёмкость агломерата, кДж/(кг * С)' },
    { name: 'heatCapacityOfPellets', description: 'Теплоёмкость окатышей, кДж/(кг * С)' },
    { name: 'heatCapacityOfCoke', description: 'Теплоёмкость кокса, кДж/(кг * С)' },
    { name: 'acceptedTemperatureOfBackupZone', description: 'Принятое значение температуры "резервной зоны", С' },
    { name: 'proportionOfHeatLossesOfLowerPart', description: 'Доля тепловых потерь через нижнюю часть печи, доли ед.' },
    { name: 'averageSizeOfPieceCharge', description: 'Средний размер куска шихты, м' }
    { name: 'HeatOfBurningOfNaturalGasOnFarms', description: 'Теплота горения природного газа на фурмах, кДж/м3' }
    { name: 'HeatOfIncompleteBurningCarbonOfCoke', description: 'Теплота неполного горения углерода кокса, кДж/кг' }
    { name: 'TemperatureOfCokeThatCameToTuyeres', description: 'Температура кокса, пришедшего к фурмам, °C' }
]

export const RESULT_FIELDS =
[
    { name: 'averageSectionalAreaOfFurnaceShaft', description: 'Средняя площадь сечения шахты печи, м2' },
    { name: 'gasFiltrationFurnaceShaftSpeed', description: 'Скорость фильтрации газа через шахту печи, м/с' },
    { name: 'eatCapacityOfDiatomicGasesAtBlastTemperature', description: 'Теплоемкость двуатомных газов при температуре дутья, кДж/(м3*С)' },
    { name: 'heatCapacityOfWaterVaporAtBlastTemperature', description: 'Теплоемкость паров воды при температур дутья, кДж/(м3*С)' },
    { name: 'degreeOfDirectRecovery', description: 'Степень прямого восстановления, доли ед.' },
    { name: 'amountOfCokeCarbonCameIntoFurnace', description: 'Количество пришедшего в печь углерода кокса, кг/т чугуна' },
    { name: 'carbonConsumptionForIronReduction', description: 'Расход углерода на прямое восстановление железа, кг/т чугуна' },
    { name: 'carbonСonsumptionForCastChugunReduction', description: 'Расход углерода на восстановление примесей чугуна, кг/т чугуна' },
    { name: 'carbonConsumptionForMethaneFormation', description: 'Расход углерода на образование метана, кг/т чугуна' },
    { name: 'amountOfCarbonOfCokeBurningAtTuyeres', description: 'Количество углерода кокса, сгорающего у фурм (Сф), кг/т чугуна' },
    { name: 'consumptionOfNaturalGasPerOneKgOfCarbonOfCoke', description: 'Расход природного газа на 1 кг углерода кокса, сгорающего у фурм, м3/кг*Сф' },
    { name: 'consumptionOfNaturalGasPerOneKgOfOfCoke', description: 'Расход дутья на сжигание 1 кг кокса, сгорающего у фурм, м3/кг*Сф' },
    { name: 'blastConsumptionForBurningOneMeterCoubOfNaturalGas', description: 'Расход дутья на сжигание 1 м3 природного газа, м3/м3' },
    { name: 'specificBlastConsumption', description: 'Удельный расход дутья, м3/т чугуна' },
    { name: 'amountOfGorenjeGasesDuringCombustionOneKgOfCarbonCoke', description: 'Количество горновых газов при горении 1 кг углерода кокса, сгорающего у фурм, м3/кг Сф' },
    { name: 'numberOfFurnaceGasesAtConversionOfOneMeterCoubOfGas', description: 'Количество горновых газов при конверсии 1 м3 газа, м3/м3' },
    { name: 'furnaceGasOutput', description: 'Выход горнового газа, м3/т чугуна' },
    { name: 'amountOfHeatFromGorenjeCoke', description: 'Количество тепла от горения кокса, кДж/кг чугуна' },
    { name: 'heatOfHeatedBlast', description: 'Тепло нагретого дутья, кДж/кг чугуна' },
    { name: 'heatOfNaturalGasConversion', description: 'Тепло конверсии природного газаа, кДж/кг чугуна' },
    { name: 'heatCapacityOfGasAtTemperatureOfReserveZone', description: 'Теплоемкость газа при температуре "резервной зоны", кДж/(м3*С)' },
    { name: 'usefulArrivalOfHeatInLowerZoneOfTheFurnace', description: '"Полезный" приход тепла в нижнюю зону печи, кДж/т чугуна' },
    { name: 'amountOfHeatEnteringLlowerZoneOfFurnaceWithCharge', description: 'Количество тепла, поступающего в нижнюю зону печи с шихтой при температуре "резервной зоны", кДж/т чугуна' },
    { name: 'heatCostsForDirectIronRecovery', description: 'Затраты тепла на прямое восстановление железа, кДж/т чугуна' },
    { name: 'heatLossesToEnvironmentThrough', description: 'Тепловые потери в окружающюю среду через фурменный пояс, распар и заплечики, кДж/т чугуна' },
    { name: 'calculatedGeneralizingParameter', description: 'Расчетный обобщающий параметр (Qp), [-]' },
    { name: 'optimalHeatConsumptionForSmeltingOneTonOfCastIron', description: 'Оптимальные затраты тепла на выплавку 1 тонны чугуна, кДж/т чугуна' },
    { name: 'indexOfTheBottomOfTheFurnace', description: 'ИНДЕКС НИЗА ПЕЧИ' },
    { name: 'valueOfHeatLossesInLowerZoneOfFurnace', description: 'Значение доли тепловых потерь в нижней зоне печи при условии i=1,0' },
    { name: 'trueHeatCapacityOfGrateGas', description: 'Истинная теплоемкость колошникового газа, кДж/(м3*С)' },
    { name: 'thermalConductivityOfGrateGas', description: 'Теплопроводность колошникового газа, Вт/(м*С)' },
    { name: 'kinematicViscosityOfGrateGas', description: 'Кинематическая вязкость колошникового газа, м2/с' },
    { name: 'volumetricHeatTransferCoefficient', description: 'Объемный коэффициент теплообмена, кВт/(м3*°С)' },
    { name: 'chargeFlowRatePassingThroughFurnaceShaft', description: 'Расход шихты, проходящий через шахту печи, кг/с' },
    { name: 'averageHeatCapacityOfCharge', description: 'Средняя теплоемкость шихты, кДж/(кг*°С)' },
    { name: 'intermediateNumerator', description: 'Промежуточные расчетные данные (числитель)' },
    { name: 'intermediateDenominator', description: 'Промежуточные расчетные данные (знаменатель)' },
    { name: 'intermediateRatio', description: 'Промежуточные расчетные данные (отношение)' },
    { name: 'intermediateExhibitor', description: 'Промежуточные расчетные данные (экспонента)' },
    { name: 'indexOfTheFurnaceTop', description: 'Индекс верха печи' },
    { name: 'blastConsumptionRequiredForBurningOneKgOfCarbonCoke', description: 'Расход дутья, необходимый для сжигания 1 кг углерода кокса, м3/кг' },
    { name: 'blastConsumptionForConversionOfOneMeterCoubOfNaturalGas', description: 'Расход дутья, необходимый для конверсии 1 м3 природного газа, м3/м3' },
    { name: 'outputOfTheTuyereGasBurningAtTheTuyeres', description: 'Выход фурменного газа в расчёте на 1 кг углерода кокса, сгорающего у фурм, м3/кг' },
    { name: 'outputOfTuyereGasOfNaturalGasDuringСonversion', description: 'Выход фурменного газа из 1 м3 природного газа при его конверсии в фурменном очаге, м3/м3' },
    { name: 'heatCapacityOfDiatomicGasesAtHotBlastTemperature', description: 'Теплоёмкость двухатомных газов при температуре горячего дутья, кДж/(м3 * К)' },
    { name: 'heatCapacityOfWaterVaporAtHotBlastTemperature', description: 'Теплоёмкость паров воды при температуре горячего дутья, кДж/(м3 * К)' },
    { name: 'heatContentOfHotBlast', description: 'Теплосодержание горячего дутья за вычетом теплоты разложения влаги дутья, кДж/м3' },
    { name: 'heatContentOfCarbonOfCokeToTuyeres', description: 'Теплосодержание углерода кокса пришедшего к фурмам, кДж/кг' },
    { name: 'naturalGasConsumptionPerOneKgOfCoke', description: 'Расход природного газа в расчете на 1 кг кокса, приходящего к фурмам, м3/кг' },
    { name: 'heatContentOfFurnaceGases', description: 'Теплосодержание горновых газов, кДж/м3' },
    { name: 'theoreticalBurningTemperatureOfCarbonCoke', description: 'Теоретическая температура горения углерода кокса, °С' },
    { name: 'resultDate', description: 'Дата проведения расчёта' }
]